name: Build & Push Docker to ACR

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-acr:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Login to Azure
    - name: Azure Login
      uses: azure/login@v2
      # Alternatively, you can use individual parameters like
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Azure subscription
      run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Step 3: Login to ACR
    - name: Login to Azure Container Registry
      run: az acr login --name xhasanacr4785adab

    # Step 4: Build Docker image locally
    - name: Build Docker image
      run: |
        IMAGE_TAG=myapp:latest
        docker build -t $IMAGE_TAG .

    # Step 5: Tag image for ACR
    - name: Tag image for ACR
      run: |
        IMAGE_TAG=myapp:latest
        docker tag $IMAGE_TAG xhasanacr4785adab.azurecr.io/myapp:latest

    # Step 6: Push image to ACR
    - name: Push image to ACR
      run: |
        docker push xhasanacr4785adab.azurecr.io/myapp:latest

    # Step 7: Deploy to Azure Container App
    - name: Deploy to Azure Container App
      run: |
        az containerapp update \
          --name xhasanxxx9cb708b8 \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image xhasanacr4785adab.azurecr.io/myapp:latest
          --target-port 80 \
          --ingress external
          --output none

